---
name: Infrastucture Deployment DO
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure DigitalOcean Credentials
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          echo "Configuring DigitalOcean credentials..."
          export DIGITALOCEAN_TOKEN="$DIGITALOCEAN_TOKEN"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5
      - name: Change Directory to Infrastructure
        run: cd K8s_Infra/
      - name: Terraform Init
        run: |
          cd K8s_Infra
          terraform init -backend=false
      - name: Terraform Validate
        run: |
          cd K8s_Infra
          terraform validate
      - name: Terraform Plan
        run: |
          cd K8s_Infra
          terraform plan -out=tfplan -backend=false
      - name: Apply and Save Terraform State
        run: |
          cd K8s_Infra
          terraform apply -backend=false --auto-approve tfplan
