name: Infrastucture Deployment DO
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Spaces Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: sf03  # Or your Spaces region
      - name: Configure DigitalOcean Credentials
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }} # For doctl or other DO interaction

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # For custom version
          terraform_version: 1.5.5 # Or latest stable

      - name: Terraform Init and Plan
        working-directory: ./K8s_Infra
        run: |
          terraform init
          terraform validate
          terraform plan -var do_token=${{ secrets.DIGITALOCEAN_TOKEN }} # Pass variable here

      - name: Terraform Apply
        working-directory: ./K8s_Infra
        env:
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }} # Pass variable here
        run: terraform apply --auto-approve